### ISSUE TITLE
Add a 'Repeat password' field to the signup page

### ISSUE THREAD

**Issue by jacekode** [jacekode/lang-control#3]
Also add custom JavaScript validation which would check that both password fields' values are equal and prevent the form from submitting if they're not.

**Comment by duncanwhyte** [comment]
Hello. I was interested on working on this issue however I am having trouble launching the app. When I try to run the app on vscode I get this error. Error: Main method not found in the file, please define the main method as: public static void main(String[] args). When I try run it from the cmd I also get this error along with 4 other errors but this is the first one. error: package org.springframework.boot does not exist.

**Comment by duncanwhyte** [comment]
Hello. Just realised I dont need to run the app. I can just manipulate the signUp.html file. Is this issue still open. Happy to help out on it.

**Comment by jacekode** [comment]
Hi, the main method is located at `src/main/java/`langcontrol/app/LangControlApplication.java`.  I tried to run it on vs code and indeed it throws errors but that's because the test classes contain compile-time errors. It's a shame of me I still haven't done it but I'm doing it right now.  Also, the project uses Maven so the Maven for Java extension might help.
In any case, the issue is open and you can do it without running the app for the time being.
